import { type NextPage } from "next";
import Head from "next/head";
import { useUser, SignIn, UserButton } from "@clerk/nextjs";
import { api } from "~/utils/api";

const Home: NextPage = () => {
  const { isLoaded, isSignedIn, user } = useUser();
  const { data } = api.posts.getAll.useQuery();
  console.log(user);
  console.log(data);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex   min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
          {data && data.map((el) => <div key={el.id}>{el.content}</div>)}
        <UserButton />
        <SignIn />
        <div>
        </div>
      </main>
    </>
  );
};

export default Home;
